baseURL = "https://stones.computer"
languageCode = "en-gb"
title = "Stones that calculate â€“ Post-Digital Materiality"
disableKinds = ["page", "taxonomyTerm"]

[outputFormats]
  [outputFormats.Items]
	  mediaType = "application/json"
	  baseName = "items"
	  isPlainText = true
	  notAlternative = true

[params]
  description = "Post-Digital Materiality"
  contentTypes = ["sources"]
  listItemTypes = ["sources", "articles", "projects"]

[outputs]
  home = ["HTML", "Items"]

[markup.goldmark.renderer]
  unsafe = true